import CartFE from "./Components/Cart";
import Nav from "./Components/Nav";
import "./globals.css";
import Providers from "./provider/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0d1117]">
        <Providers>
        <Nav/>
        {children}
        <CartFE/>
        </Providers>
      </body>
    </html>
  );
}
